
service: git-lambda

provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  region: us-east-1

functions:
  generateRandomNumber:
    handler: src/handler.generateRandomNumber
    events:
      - http:
          path: random-number
          method: get
          cors: true # Add CORS if needed
    timeout: 60 #seconds
    memorySize: 128 #megabytes
   generateRandomNumber:
    handler: src/handler.home
    events:
      - http:
          path: home
          method: get
          cors: true # Add CORS if needed
    timeout: 60 #seconds
    memorySize: 128 #megabytes
   generateRandomNumber:
    handler: src/handler.author
    events:
      - http:
          path: author
          method: get
          cors: true # Add CORS if needed
    timeout: 60 #seconds
    memorySize: 128 #megabytes
    